### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dnnspark** [dnnspark/experiment_interface#1]
- [ ] visualize using visdom
  - [ ] record train loss, val loss, val accuracy using dataframe.
  - [ ] add dataframe buffer to TrainContext (how to decide columns?).
  - [ ] Flush to csv file regularly.
- [ ] load checkpoint model 
- [ ]
